user_file = '../data/user_index2entity_id.txt'
item_file = '../data/item_index2entity_id.txt'
rating_file = '../data/ratings.txt'
rating_final_file = '../data/ratings_final.txt'
kg_file = '../data/kg.txt'
kg_final_user_file = '../data/kg_final_user.txt'
kg_final_item_file = '../data/kg_final_item.txt'
lda_model = '../data/lda_datas/lda.model'
dict_path = '../data/lda_datas/lda.dict'
index_path = '../data/lda_datas/index'

id2text = '../data/id2text'
ui2index = '../data/ui2index'
